In [2]:
import numpy as np
print(np.__version__)

2.4.2


In [3]:
#intro to arrays and multidimensional arrays
array=np.array([[1,2,3,4],
                [5,6,7,8],
                [2,4,6,8],
                [1,3,5,7]])
print(array.ndim)#number of dimensions
print(array.shape)
a=array[0,0]+array[0,1]+array[2,0] #multidemensional indexing
print(a)

2
(4, 4)
5


In [4]:
#slicing
sarray=np.array([[1,2,3,4],
                [5,6,7,8],
                [2,4,6,8],
                [1,3,5,7]])
#array[start:end:step]
print(sarray[0::2])
print()
print(array[::-1])

#array[row_start:row_end:row_step, col_start:col_end:col_step]
print("\n",sarray[:,-1])
print()
print(sarray[0:4,0:1],"\n")
print(sarray[:,1::1],"\n")
print(sarray[0:2,0:2])

[[1 2 3 4]
 [2 4 6 8]]

[[1 3 5 7]
 [2 4 6 8]
 [5 6 7 8]
 [1 2 3 4]]

 [4 8 8 7]

[[1]
 [5]
 [2]
 [1]] 

[[2 3 4]
 [6 7 8]
 [4 6 8]
 [3 5 7]] 

[[1 2]
 [5 6]]


below code is arithmetic operations

In [5]:
#arithmetic #1
#scalar
array=np.array([1,2,3])
print(array+1)
print(array*2)

#vectorized math functions
n_array=np.array([2.01,3,1.49,4,5,6])
print(np.sqrt(n_array))
print(np.round(n_array))
print(np.floor(n_array))
print(np.ceil(n_array))

#builtin
print(np.pi)

#find circumference and area of radii
radii=np.array([1,2,3,4,5])
print("circumference = ",radii*2*np.pi)
print("area = ",radii**2*np.pi)

[2 3 4]
[2 4 6]
[1.41774469 1.73205081 1.22065556 2.         2.23606798 2.44948974]
[2. 3. 1. 4. 5. 6.]
[2. 3. 1. 4. 5. 6.]
[3. 3. 2. 4. 5. 6.]
3.141592653589793
circumference =  [ 6.28318531 12.56637061 18.84955592 25.13274123 31.41592654]
area =  [ 3.14159265 12.56637061 28.27433388 50.26548246 78.53981634]


In [6]:
#arithmetic #2
#elementwise arithmetic
array1=np.array([1,2,3])
array2=np.array([4,5,6])

print(array1+array2)
print(array1*array2)
print(array1**array2)

[5 7 9]
[ 4 10 18]
[  1  32 729]


In [7]:
#comparison operators
scores=np.array([2,3,4,5,6,7,8,9,10])
print(scores%2==0)
print(scores>=4)
scores[scores<5]=0
print(scores)


[ True False  True False  True False  True False  True]
[False False  True  True  True  True  True  True  True]
[ 0  0  0  5  6  7  8  9 10]


end of arithmetic, next broadcasting

In [8]:
#broadcasting in numpy allows arithmetic operations between arrays of different shapes, by virtually expanding the smaller array to match the shape of the larger one without actually copying data(means the data is only read that way, without creating new values).
#the dimensions of the arrays are compatible for broadcasting if:
#1. they are equal, or
#2. one of them is 1
array1=np.array([[1,2,3,4]])
array2=np.array([[1],[2],[3],[4]])
print(array1.shape)
print(array2.shape)
#the shape of array1 is (1,4) and the shape of array2 is (4,1). According to the broadcasting rules, these shapes are compatible because:
#- The second dimension for 4 there is 1 in array2, so it can be broadcasted to match the 4 in array1. likewise....
print(array1+array2)
#array1 is broadcasted to match the shape of array2, resulting in a 4x4 array where each row of array1 is added to the corresponding element of array2.


#if it was 1,4 and 2,4 it would give error, but 4,1 and 4,4 would work



#simple example
array1=np.array([[1,2,3,4,5,6,7,8,9,10]])
array2=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(array1.shape,array2.shape)
print("multiplication table\n",array1*array2)

(1, 4)
(4, 1)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
(1, 10) (10, 1)
multiplication table
 [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


**Aggregate functions**

In [9]:
#aggregate functions -> summarize data and typically return a single value
array=np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
print("sum is ", np.sum(array))
print("mean is ", np.mean(array))
print("max is ", np.max(array))
print("std is ", np.std(array))
print(np.argmin(array)) #index of min value
print("variance is ", np.var(array))
print("axis=0 sum is ", np.sum(array, axis=0)) #column wise

sum is  55
mean is  5.5
max is  10
std is  2.8722813232690143
0
variance is  8.25
axis=0 sum is  [ 7  9 11 13 15]


***filtering***

In [10]:
#filtering is selecting elements from an array based on a condition
marks=np.array([[23,14,15,22,25],
                [24,23,22,24,25]])

filtered_data=marks[marks>20]
print(filtered_data)#2d array is converted to 1d array with only the elements satisfying the condition

f2=marks[(marks<24) & (marks>=20)]#& as numpy is c style
print(f2)


#slower method of filtering using np.where
good_marks=np.where(marks>=23, "good", "bad")
print(good_marks)

[23 22 25 24 23 22 24 25]
[23 22 23 22]
[['good' 'bad' 'bad' 'bad' 'good']
 ['good' 'good' 'bad' 'good' 'good']]


Problem 1 generate random numbers

In [21]:
#generating random numbers
rng=np.random.default_rng()#we can use seed if we want to generate the same random numbers every time
print(rng.integers(low=1,high=101))#101 is exclusive, till 100 only

print(rng.integers(1,101,2))#size = 2
print(rng.integers(1,101,(2,3)))#size =2*3

#random floats
print(rng.random())#between 0 and 1

np.random.seed(0)#setting affects all random number generation after this line
print(np.random.uniform(0,10))#uniform is used to generate random floats in a specified range, but if we call it without arguments, it behaves the same as np.random() and generates a random float between 0 and 1.(we can also set size)


16
[7 5]
[[50 71 57]
 [96 29 14]]
0.5152469543175665
5.4881350392732475


Problem 2 shiffle a array


In [12]:
import numpy as np
rng=np.random.default_rng()
array=np.array([1,2,3,4,5])
print(array)
rng.shuffle(array)
print(array)


#for random choice
single_number = rng.choice(array)#we can also set size
print(single_number)

[1 2 3 4 5]
[3 4 2 1 5]
2
